=== dzurikmiroslav/esp32-evse-web-i18n/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "nav": {
      "type": "object",
      "properties": {
        "home": {
          "type": "string"
        },
        "settings": {
          "type": "string"
        },
        "about": {
          "type": "string"
        },
        "charging": {
          "type": "string"
        },
        "network": {
          "type": "string"
        },
        "serial": {
          "type": "string"
        },
        "modbus": {
          "type": "string"
        },
        "scheduler": {
          "type": "string"
        },
        "files": {
          "type": "string"
        },
        "script": {
          "type": "string"
        },
        "management": {
          "type": "string"
        },
        "system": {
          "type": "string"
        },
        "nextion": {
          "type": "string"
        },
        "selectLanguage": {
          "type": "string"
        },
        "toggleTheme": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "home",
        "settings",
        "about",
        "charging",
        "network",
        "serial",
        "modbus",
        "scheduler",
        "files",
        "script",
        "management",
        "system",
        "nextion",
        "selectLanguage",
        "toggleTheme"
      ]
    },
    "pendingAuthorization": {
      "type": "string"
    },
    "chargingLimitReached": {
      "type": "string"
    },
    "evConnected": {
      "type": "string"
    },
    "charging": {
      "type": "string"
    },
    "error": {
      "type": "string"
    },
    "notAvailable": {
      "type": "string"
    },
    "evNotConnected": {
      "type": "string"
    },
    "sessionTime": {
      "type": "string"
    },
    "chargingTime": {
      "type": "string"
    },
    "power": {
      "type": "string"
    },
    "consumption": {
      "type": "string"
    },
    "totalConsumption": {
      "type": "string"
    },
    "resetTotalConsumption": {
      "type": "string"
    },
    "confirmResetTotalConsumption": {
      "type": "string"
    },
    "enabled": {
      "type": "string"
    },
    "authorize": {
      "type": "string"
    },
    "sessionLimit": {
      "type": "string"
    },
    "underPower": {
      "type": "string"
    },
    "none": {
      "type": "string"
    },
    "$none": {
      "type": "string"
    },
    "yes": {
      "type": "string"
    },
    "no": {
      "type": "string"
    },
    "submit": {
      "type": "string"
    },
    "reset": {
      "type": "string"
    },
    "reload": {
      "type": "string"
    },
    "cancel": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "deviceInfo": {
      "type": "string"
    },
    "uptime": {
      "type": "string"
    },
    "temperature": {
      "type": "string"
    },
    "temperatureSensorCount": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "dateOfBuild": {
      "type": "string"
    },
    "idfVersion": {
      "type": "string"
    },
    "ip": {
      "type": "string"
    },
    "mac": {
      "type": "string"
    },
    "chip": {
      "type": "string"
    },
    "chipCores": {
      "type": "string"
    },
    "chipRevision": {
      "type": "string"
    },
    "heap": {
      "type": "string"
    },
    "moreDetails": {
      "type": "string"
    },
    "free": {
      "type": "string"
    },
    "allocated": {
      "type": "string"
    },
    "largestFreeBlock": {
      "type": "string"
    },
    "minFree": {
      "type": "string"
    },
    "deviceName": {
      "type": "string"
    },
    "proximity": {
      "type": "string"
    },
    "socketLock": {
      "type": "string"
    },
    "rcm": {
      "type": "string"
    },
    "energyMeter": {
      "type": "string"
    },
    "energyMeterThreePhases": {
      "type": "string"
    },
    "auxInputs": {
      "type": "string"
    },
    "auxOutputs": {
      "type": "string"
    },
    "auxAnalogInputs": {
      "type": "string"
    },
    "serials": {
      "type": "string"
    },
    "maxChargingCurrent": {
      "type": "string"
    },
    "chargingCurrent": {
      "type": "string"
    },
    "consumptionLimit": {
      "type": "string"
    },
    "chargingTimeLimit": {
      "type": "string"
    },
    "underPowerLimit": {
      "type": "string"
    },
    "requireAuth": {
      "type": "string"
    },
    "socketOutlet": {
      "type": "string"
    },
    "temperatureThreshold": {
      "type": "string"
    },
    "operatingTime": {
      "type": "string"
    },
    "breakTime": {
      "type": "string"
    },
    "retryCount": {
      "type": "string"
    },
    "detection": {
      "type": "string"
    },
    "unlockedHigh": {
      "type": "string"
    },
    "lockedHigh": {
      "type": "string"
    },
    "mode": {
      "type": "string"
    },
    "dummy": {
      "type": "string"
    },
    "currentSensing": {
      "type": "string"
    },
    "currentAndVoltageSensing": {
      "type": "string"
    },
    "acVoltage": {
      "type": "string"
    },
    "threePhases": {
      "type": "string"
    },
    "ssid": {
      "type": "string"
    },
    "user": {
      "type": "string"
    },
    "password": {
      "type": "string"
    },
    "loading": {
      "type": "string"
    },
    "uploading": {
      "type": "string"
    },
    "noWifiFound": {
      "type": "string"
    },
    "systemLogs": {
      "type": "string"
    },
    "modbus": {
      "type": "string"
    },
    "nextionDisplay": {
      "type": "string"
    },
    "script": {
      "type": "string"
    },
    "atCommands": {
      "type": "string"
    },
    "baudRate": {
      "type": "string"
    },
    "dataBits": {
      "type": "string"
    },
    "stopBits": {
      "type": "string"
    },
    "parity": {
      "type": "string"
    },
    "disable": {
      "type": "string"
    },
    "even": {
      "type": "string"
    },
    "odd": {
      "type": "string"
    },
    "tcpServer": {
      "type": "string"
    },
    "unitId": {
      "type": "string"
    },
    "timezone": {
      "type": "string"
    },
    "time": {
      "type": "string"
    },
    "setCurrent": {
      "type": "string"
    },
    "ntp": {
      "type": "string"
    },
    "serverFromDhcp": {
      "type": "string"
    },
    "server": {
      "type": "string"
    },
    "schedules": {
      "type": "string"
    },
    "noSchedules": {
      "type": "string"
    },
    "addSchedule": {
      "type": "string"
    },
    "action": {
      "type": "string"
    },
    "enableCharging": {
      "type": "string"
    },
    "chargerAvailable": {
      "type": "string"
    },
    "chargingCurrent6A": {
      "type": "string"
    },
    "chargingCurrent8A": {
      "type": "string"
    },
    "chargingCurrent10A": {
      "type": "string"
    },
    "clear": {
      "type": "string"
    },
    "remove": {
      "type": "string"
    },
    "monday": {
      "type": "string"
    },
    "tuesday": {
      "type": "string"
    },
    "wednesday": {
      "type": "string"
    },
    "thursday": {
      "type": "string"
    },
    "friday": {
      "type": "string"
    },
    "saturday": {
      "type": "string"
    },
    "sunday": {
      "type": "string"
    },
    "root": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "size": {
      "type": "string"
    },
    "download": {
      "type": "string"
    },
    "edit": {
      "type": "string"
    },
    "_delete": {
      "type": "string"
    },
    "emptyDirectory": {
      "type": "string"
    },
    "createDirectory": {
      "type": "string"
    },
    "createFile": {
      "type": "string"
    },
    "uploadFile": {
      "type": "string"
    },
    "fileName": {
      "type": "string"
    },
    "directoryName": {
      "type": "string"
    },
    "fileContent": {
      "type": "string"
    },
    "fileSaved": {
      "type": "string"
    },
    "directorySaved": {
      "type": "string"
    },
    "fileDeleted": {
      "type": "string"
    },
    "directoryDeleted": {
      "type": "string"
    },
    "fileUploaded": {
      "type": "string"
    },
    "fileTooLarge": {
      "type": "string"
    },
    "components": {
      "type": "string"
    },
    "noComponents": {
      "type": "string"
    },
    "configuration": {
      "type": "string"
    },
    "noComponentConfig": {
      "type": "string"
    },
    "autoReload": {
      "type": "string"
    },
    "output": {
      "type": "string"
    },
    "restart": {
      "type": "string"
    },
    "confirmRestart": {
      "type": "string"
    },
    "firmware": {
      "type": "string"
    },
    "channel": {
      "type": "string"
    },
    "checkForUpdate": {
      "type": "string"
    },
    "upgradeTo": {
      "type": "string"
    },
    "noUpdateAvailable": {
      "type": "string"
    },
    "uploadFirmware": {
      "type": "string"
    },
    "binariesFromReleases1": {
      "type": "string"
    },
    "binariesFromReleases2": {
      "type": "string"
    },
    "writeFirmware": {
      "type": "string"
    },
    "willBeRestart": {
      "type": "string"
    },
    "reloadInSeconds1": {
      "type": "string"
    },
    "reloadInSeconds2": {
      "type": "string"
    },
    "reloadNow": {
      "type": "string"
    },
    "successfullyUpdatedFirmware": {
      "type": "string"
    },
    "successfullyUpdated": {
      "type": "string"
    },
    "scriptReloaded": {
      "type": "string"
    },
    "networkError": {
      "type": "string"
    },
    "reloadPage": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "touch": {
      "type": "string"
    },
    "flashSize": {
      "type": "string"
    },
    "noNextionConnected": {
      "type": "string"
    },
    "uploadProgram": {
      "type": "string"
    },
    "writeProgram": {
      "type": "string"
    },
    "staticIp": {
      "type": "string"
    },
    "gateway": {
      "type": "string"
    },
    "netmask": {
      "type": "string"
    },
    "dns": {
      "type": "string"
    },
    "wifiAccessPoint": {
      "type": "string"
    },
    "wifiAccessPointAutoStop": {
      "type": "string"
    },
    "wifiStation": {
      "type": "string"
    },
    "discovery": {
      "type": "string"
    },
    "hostname": {
      "type": "string"
    },
    "instanceName": {
      "type": "string"
    },
    "rssi": {
      "type": "string"
    },
    "panicReboot": {
      "type": "string"
    },
    "acknowledge": {
      "type": "string"
    },
    "successfullyAcknowledged": {
      "type": "string"
    },
    "httpErrorValues": {
      "type": "object",
      "properties": {
        "400": {
          "type": "string"
        },
        "404": {
          "type": "string"
        },
        "413": {
          "type": "string"
        },
        "415": {
          "type": "string"
        },
        "500": {
          "type": "string"
        },
        "512": {
          "type": "string"
        },
        "513": {
          "type": "string"
        },
        "520": {
          "type": "string"
        },
        "521": {
          "type": "string"
        },
        "522": {
          "type": "string"
        },
        "523": {
          "type": "string"
        },
        "531": {
          "type": "string"
        },
        "532": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "400",
        "404",
        "413",
        "415",
        "500",
        "512",
        "513",
        "520",
        "521",
        "522",
        "523",
        "531",
        "532"
      ]
    },
    "errorValues": {
      "type": "object",
      "properties": {
        "pilot_fault": {
          "type": "string"
        },
        "diode_short": {
          "type": "string"
        },
        "lock_fault": {
          "type": "string"
        },
        "unlock_fault": {
          "type": "string"
        },
        "rcm_triggered": {
          "type": "string"
        },
        "rcm_selftest_fault": {
          "type": "string"
        },
        "temperature_high": {
          "type": "string"
        },
        "temperature_fault": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "pilot_fault",
        "diode_short",
        "lock_fault",
        "unlock_fault",
        "rcm_triggered",
        "rcm_selftest_fault",
        "temperature_high",
        "temperature_fault"
      ]
    },
    "energyMeterValues": {
      "type": "object",
      "properties": {
        "cur_vlt": {
          "type": "string"
        },
        "cur": {
          "type": "string"
        },
        "none": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "cur_vlt",
        "cur",
        "none"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "nav",
    "pendingAuthorization",
    "chargingLimitReached",
    "evConnected",
    "charging",
    "error",
    "notAvailable",
    "evNotConnected",
    "sessionTime",
    "chargingTime",
    "power",
    "consumption",
    "totalConsumption",
    "resetTotalConsumption",
    "confirmResetTotalConsumption",
    "enabled",
    "authorize",
    "sessionLimit",
    "underPower",
    "none",
    "$none",
    "yes",
    "no",
    "submit",
    "reset",
    "reload",
    "cancel",
    "status",
    "deviceInfo",
    "uptime",
    "temperature",
    "temperatureSensorCount",
    "version",
    "dateOfBuild",
    "idfVersion",
    "ip",
    "mac",
    "chip",
    "chipCores",
    "chipRevision",
    "heap",
    "moreDetails",
    "free",
    "allocated",
    "largestFreeBlock",
    "minFree",
    "deviceName",
    "proximity",
    "socketLock",
    "rcm",
    "energyMeter",
    "energyMeterThreePhases",
    "auxInputs",
    "auxOutputs",
    "auxAnalogInputs",
    "serials",
    "maxChargingCurrent",
    "chargingCurrent",
    "consumptionLimit",
    "chargingTimeLimit",
    "underPowerLimit",
    "requireAuth",
    "socketOutlet",
    "temperatureThreshold",
    "operatingTime",
    "breakTime",
    "retryCount",
    "detection",
    "unlockedHigh",
    "lockedHigh",
    "mode",
    "dummy",
    "currentSensing",
    "currentAndVoltageSensing",
    "acVoltage",
    "threePhases",
    "ssid",
    "user",
    "password",
    "loading",
    "uploading",
    "noWifiFound",
    "systemLogs",
    "modbus",
    "nextionDisplay",
    "script",
    "atCommands",
    "baudRate",
    "dataBits",
    "stopBits",
    "parity",
    "disable",
    "even",
    "odd",
    "tcpServer",
    "unitId",
    "timezone",
    "time",
    "setCurrent",
    "ntp",
    "serverFromDhcp",
    "server",
    "schedules",
    "noSchedules",
    "addSchedule",
    "action",
    "enableCharging",
    "chargerAvailable",
    "chargingCurrent6A",
    "chargingCurrent8A",
    "chargingCurrent10A",
    "clear",
    "remove",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "root",
    "name",
    "size",
    "download",
    "edit",
    "_delete",
    "emptyDirectory",
    "createDirectory",
    "createFile",
    "uploadFile",
    "fileName",
    "directoryName",
    "fileContent",
    "fileSaved",
    "directorySaved",
    "fileDeleted",
    "directoryDeleted",
    "fileUploaded",
    "fileTooLarge",
    "components",
    "noComponents",
    "configuration",
    "noComponentConfig",
    "autoReload",
    "output",
    "restart",
    "confirmRestart",
    "firmware",
    "channel",
    "checkForUpdate",
    "upgradeTo",
    "noUpdateAvailable",
    "uploadFirmware",
    "binariesFromReleases1",
    "binariesFromReleases2",
    "writeFirmware",
    "willBeRestart",
    "reloadInSeconds1",
    "reloadInSeconds2",
    "reloadNow",
    "successfullyUpdatedFirmware",
    "successfullyUpdated",
    "scriptReloaded",
    "networkError",
    "reloadPage",
    "model",
    "touch",
    "flashSize",
    "noNextionConnected",
    "uploadProgram",
    "writeProgram",
    "staticIp",
    "gateway",
    "netmask",
    "dns",
    "wifiAccessPoint",
    "wifiAccessPointAutoStop",
    "wifiStation",
    "discovery",
    "hostname",
    "instanceName",
    "rssi",
    "panicReboot",
    "acknowledge",
    "successfullyAcknowledged",
    "httpErrorValues",
    "errorValues",
    "energyMeterValues"
  ]
}

=== dzurikmiroslav/esp32-evse-web-i18n/ru.json
{
  "nav": {
    "home": "Домой",
    "settings": "Установки",
    "about": "О программе",
    "charging": "Зарядка",
    "network": "Network",
    "serial": "Serial",
    "modbus": "Modbus",
    "scheduler": "Планировщик",
    "files": "Файлы",
    "script": "Сценарий",
    "management": "Управление",
    "system": "Система",
    "nextion": "Nextion",
    "selectLanguage": "Выбор языка",
    "toggleTheme": "Сменить тему"
  },
  "pendingAuthorization": "Необходима авторизация",
  "chargingLimitReached": "Достигнут лимит зарядки",
  "evConnected": "Подключено к авто",
  "charging": "Зарядка",
  "error": "Ошибка",
  "notAvailable": "Невозможно",
  "evNotConnected": "Не подключено к авто",
  "sessionTime": "Время сессии",
  "chargingTime": "Время зарядки",
  "power": "Мощность",
  "consumption": "Потребление",
  "totalConsumption": "Общее потребление",
  "resetTotalConsumption": "Сброс общего потребление",
  "confirmResetTotalConsumption": "Сбросить общее потребление?",
  "enabled": "Включено",
  "authorize": "Авторизация",
  "sessionLimit": "Лимит сессии",
  "underPower": "Низкое потребление",
  "none": "Нет",
  "$none": "нет",
  "yes": "Да",
  "no": "Нет",
  "submit": "Подтвердить",
  "reset": "Сброс",
  "reload": "Обновить",
  "cancel": "Отмена",
  "status": "Статус",
  "deviceInfo": "Информация об устройстве",
  "uptime": "Время работы",
  "temperature": "Температура",
  "temperatureSensorCount": "Число термодатчиков",
  "version": "Версия",
  "dateOfBuild": "Дата сборки",
  "idfVersion": "Версия IDF",
  "ip": "IP",
  "mac": "Mac",
  "chip": "Чип",
  "chipCores": "Число ядер",
  "chipRevision": "Ревизия чипа",
  "heap": "Heap",
  "moreDetails": "Подробнее",
  "free": "Свободно",
  "allocated": "Выделено",
  "largestFreeBlock": "Наибольший свободный блок",
  "minFree": "Минимум свободно",
  "deviceName": "Имя устройства",
  "proximity": "Сигнал PP(Proximity)",
  "socketLock": "Блокировка розетки",
  "rcm": "Монитор УЗО",
  "energyMeter": "Счетчик энергии",
  "energyMeterThreePhases": "Трехфазный счетчик энергии",
  "auxInputs": "AUX входы",
  "auxOutputs": "AUX выходы",
  "auxAnalogInputs": "AUX аналоговые входы",
  "serials": "Serial порты",
  "maxChargingCurrent": "Макс. ток зарядки",
  "chargingCurrent": "Ток зарядки",
  "consumptionLimit": "Лимит потребления",
  "chargingTimeLimit": "Лимит времени зарядки",
  "underPowerLimit": "Лимит минимального потребления",
  "requireAuth": "Требуется авторизация",
  "socketOutlet": "Розетка",
  "temperatureThreshold": "Температурный порог",
  "operatingTime": "Время работы",
  "breakTime": "Время перерыва",
  "retryCount": "Число повторов",
  "detection": "Обнаружение",
  "unlockedHigh": "Разблокировано высокое напр.",
  "lockedHigh": "Заблокировано высокое напр.",
  "mode": "Режим",
  "dummy": "Пусто",
  "currentSensing": "Измерение тока",
  "currentAndVoltageSensing": "Измерение напряжения и тока",
  "acVoltage": "AC напряжение",
  "threePhases": "Три фазы",
  "ssid": "SSID",
  "user": "User",
  "password": "Password",
  "loading": "Загрузка...",
  "uploading": "Загрузка...",
  "noWifiFound": "Не найдено WiFi",
  "systemLogs": "Системный журнал",
  "modbus": "Modbus",
  "nextionDisplay": "Nextion display",
  "script": "Сценарий",
  "atCommands":"AT команды",
  "baudRate": "Baud rate",
  "dataBits": "Data bits",
  "stopBits": "Stop bits",
  "parity": "Parity",
  "disable": "Выключен",
  "even": "Even",
  "odd": "Odd",
  "tcpServer": "TCP server",
  "unitId": "ID-устройства",
  "timezone": "Часовой пояс",
  "time": "Время",
  "setCurrent": "Установить текущее",
  "ntp": "NTP",
  "serverFromDhcp": "Сервер от DHCP",
  "server": "Сервер",
  "schedules": "Сценарии",
  "noSchedules": "Нет сценариев",
  "addSchedule": "Добавить сценарий",
  "action": "Действие",
  "enableCharging": "Включить зарядку",
  "chargerAvailable": "Зарядное устройство доступно",
  "chargingCurrent6A": "Ток зарядки 6A",
  "chargingCurrent8A": "Ток зарядки 8A",
  "chargingCurrent10A": "Ток зарядки 10A",
  "clear": "Очистить",
  "remove": "Удалить",
  "monday": "Пнд",
  "tuesday": "Втр",
  "wednesday": "Срд",
  "thursday": "Чтв",
  "friday": "Пят",
  "saturday": "Суб",
  "sunday": "Вск",
  "root": "Корень",
  "name": "Имя",
  "size": "Размер",
  "download": "Скачать",
  "edit": "Редактировать",
  "_delete": "Удалить",
  "emptyDirectory": "Папка пуста",
  "createDirectory": "Создать папку",
  "createFile": "Создать файл",
  "uploadFile": "Загрузить файл",
  "fileName": "Имя файла",
  "directoryName": "Имя папки",
  "fileContent": "Содержимое файла",
  "fileSaved": "Файл записан",
  "directorySaved": "Папка записана",
  "fileDeleted": "Файл удалён",
  "directoryDeleted": "Папка удалена",
  "fileUploaded": "Файл успешно загружен",
  "fileTooLarge": "Выбранный файл слишком большой",
  "components": "Компоненты",
  "noComponents": "Нет компонентов скрипта",
  "configuration": "Конфигурация",
  "noComponentConfig": "Компонент не имеет конфигурации",
  "autoReload": "Автозагрузка",
  "output": "Выход",
  "restart": "Рестарт",
  "confirmRestart": "Перегрузить устройство?",
  "firmware": "Прошивка",
  "channel": "Канал",
  "checkForUpdate": "Проверить наличие обновлений",
  "upgradeTo": "Обновить до",
  "noUpdateAvailable": "Нет обновлений",
  "uploadFirmware": "Загрузка прошивки",
  "binariesFromReleases1": "Использовать OTA файлы",
  "binariesFromReleases2": "релизы",
  "writeFirmware": "Записать прошивку",
  "willBeRestart": "Устройство перезапущено",
  "reloadInSeconds1": "Перегрузить  через",
  "reloadInSeconds2": "секунд",
  "reloadNow": "Перегрузить сейчас",
  "successfullyUpdatedFirmware": "Прошивка обновлена успешно",
  "successfullyUpdated": "Обновление успешно",
  "scriptReloaded": "Скрипт был перезагружен",
  "networkError": "Ошибка сети",
  "reloadPage": "Обновить страницу",
  "model": "Модель",
  "touch": "Сенсор",
  "flashSize": "Размер Flash",
  "noNextionConnected": "Не подключен Nextion дисплей",
  "uploadProgram": "Загрузить программу",
  "writeProgram": "Записать программу",
  "staticIp": "Статический IP-адрес",
  "gateway": "Шлюз",
  "netmask": "Маска подсети",
  "dns": "DNS-сервер",
  "wifiAccessPoint": "Точка доступа WiFi",
  "wifiAccessPointAutoStop": "Точка доступа автоматически отключится, если в течение одной минуты к ней никто не подключится.",
  "wifiStation": "WiFi-станция",
  "discovery": "Обнаружение",
  "hostname": "Имя хоста",
  "instanceName": "Имя экземпляра",
  "rssi": "RSSI",
  "panicReboot": "Паника перезагрузка",
  "acknowledge": "Подтвердить",
  "successfullyAcknowledged": "Успешно подтверждено",
  "httpErrorValues": {
    "400": "Ошибка запроса",
    "404": "Не найдено",
    "413": "Слишком большой размер контента",
    "415": "Неподдерживаемый тип носителя",
    "500": "Внутренняя ошибка сервера",
    "512": "Не удалось выделить память",
    "513": "Не удалось получить запрос",
    "520": "Невозможно получить информацию о последней версии",
    "521": "Не удалось обновить прошивку",
    "522": "Не удалось получить прошивку",
    "523": "Неверный файл прошивки",
    "531": "Не удалось написать программу",
    "532": "Не удалось получить программу"
  },
  "errorValues": {
    "pilot_fault": "Сбой Пилот-Сигнала",
    "diode_short": "Пробой диода",
    "lock_fault": "Ошибка блокировки",
    "unlock_fault": "Ошибка разблокировки",
    "rcm_triggered": "Сработка УЗО",
    "rcm_selftest_fault": "Сбой УЗО",
    "temperature_high": "Перегрев",
    "temperature_fault": "Сбой термодатчика"
  },
  "energyMeterValues": {
    "cur_vlt": "Ток и напряжение",
    "cur": "Ток",
    "none": "Нет"
  }
}
