=== dzurikmiroslav/esp32-evse-web-i18n/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "nav": {
      "type": "object",
      "properties": {
        "home": {
          "type": "string"
        },
        "settings": {
          "type": "string"
        },
        "about": {
          "type": "string"
        },
        "charging": {
          "type": "string"
        },
        "network": {
          "type": "string"
        },
        "serial": {
          "type": "string"
        },
        "modbus": {
          "type": "string"
        },
        "scheduler": {
          "type": "string"
        },
        "files": {
          "type": "string"
        },
        "script": {
          "type": "string"
        },
        "management": {
          "type": "string"
        },
        "system": {
          "type": "string"
        },
        "nextion": {
          "type": "string"
        },
        "selectLanguage": {
          "type": "string"
        },
        "toggleTheme": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "home",
        "settings",
        "about",
        "charging",
        "network",
        "serial",
        "modbus",
        "scheduler",
        "files",
        "script",
        "management",
        "system",
        "nextion",
        "selectLanguage",
        "toggleTheme"
      ]
    },
    "pendingAuthorization": {
      "type": "string"
    },
    "chargingLimitReached": {
      "type": "string"
    },
    "evConnected": {
      "type": "string"
    },
    "charging": {
      "type": "string"
    },
    "error": {
      "type": "string"
    },
    "notAvailable": {
      "type": "string"
    },
    "evNotConnected": {
      "type": "string"
    },
    "sessionTime": {
      "type": "string"
    },
    "chargingTime": {
      "type": "string"
    },
    "power": {
      "type": "string"
    },
    "consumption": {
      "type": "string"
    },
    "totalConsumption": {
      "type": "string"
    },
    "resetTotalConsumption": {
      "type": "string"
    },
    "confirmResetTotalConsumption": {
      "type": "string"
    },
    "enabled": {
      "type": "string"
    },
    "authorize": {
      "type": "string"
    },
    "sessionLimit": {
      "type": "string"
    },
    "underPower": {
      "type": "string"
    },
    "none": {
      "type": "string"
    },
    "$none": {
      "type": "string"
    },
    "yes": {
      "type": "string"
    },
    "no": {
      "type": "string"
    },
    "submit": {
      "type": "string"
    },
    "reset": {
      "type": "string"
    },
    "reload": {
      "type": "string"
    },
    "cancel": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "deviceInfo": {
      "type": "string"
    },
    "uptime": {
      "type": "string"
    },
    "temperature": {
      "type": "string"
    },
    "temperatureSensorCount": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "dateOfBuild": {
      "type": "string"
    },
    "idfVersion": {
      "type": "string"
    },
    "ip": {
      "type": "string"
    },
    "mac": {
      "type": "string"
    },
    "chip": {
      "type": "string"
    },
    "chipCores": {
      "type": "string"
    },
    "chipRevision": {
      "type": "string"
    },
    "heap": {
      "type": "string"
    },
    "moreDetails": {
      "type": "string"
    },
    "free": {
      "type": "string"
    },
    "allocated": {
      "type": "string"
    },
    "largestFreeBlock": {
      "type": "string"
    },
    "minFree": {
      "type": "string"
    },
    "deviceName": {
      "type": "string"
    },
    "proximity": {
      "type": "string"
    },
    "socketLock": {
      "type": "string"
    },
    "rcm": {
      "type": "string"
    },
    "energyMeter": {
      "type": "string"
    },
    "energyMeterThreePhases": {
      "type": "string"
    },
    "auxInputs": {
      "type": "string"
    },
    "auxOutputs": {
      "type": "string"
    },
    "auxAnalogInputs": {
      "type": "string"
    },
    "serials": {
      "type": "string"
    },
    "maxChargingCurrent": {
      "type": "string"
    },
    "chargingCurrent": {
      "type": "string"
    },
    "consumptionLimit": {
      "type": "string"
    },
    "chargingTimeLimit": {
      "type": "string"
    },
    "underPowerLimit": {
      "type": "string"
    },
    "requireAuth": {
      "type": "string"
    },
    "socketOutlet": {
      "type": "string"
    },
    "temperatureThreshold": {
      "type": "string"
    },
    "operatingTime": {
      "type": "string"
    },
    "breakTime": {
      "type": "string"
    },
    "retryCount": {
      "type": "string"
    },
    "detection": {
      "type": "string"
    },
    "unlockedHigh": {
      "type": "string"
    },
    "lockedHigh": {
      "type": "string"
    },
    "mode": {
      "type": "string"
    },
    "dummy": {
      "type": "string"
    },
    "currentSensing": {
      "type": "string"
    },
    "currentAndVoltageSensing": {
      "type": "string"
    },
    "acVoltage": {
      "type": "string"
    },
    "threePhases": {
      "type": "string"
    },
    "ssid": {
      "type": "string"
    },
    "user": {
      "type": "string"
    },
    "password": {
      "type": "string"
    },
    "loading": {
      "type": "string"
    },
    "uploading": {
      "type": "string"
    },
    "noWifiFound": {
      "type": "string"
    },
    "systemLogs": {
      "type": "string"
    },
    "modbus": {
      "type": "string"
    },
    "nextionDisplay": {
      "type": "string"
    },
    "script": {
      "type": "string"
    },
    "atCommands": {
      "type": "string"
    },
    "baudRate": {
      "type": "string"
    },
    "dataBits": {
      "type": "string"
    },
    "stopBits": {
      "type": "string"
    },
    "parity": {
      "type": "string"
    },
    "disable": {
      "type": "string"
    },
    "even": {
      "type": "string"
    },
    "odd": {
      "type": "string"
    },
    "tcpServer": {
      "type": "string"
    },
    "unitId": {
      "type": "string"
    },
    "timezone": {
      "type": "string"
    },
    "time": {
      "type": "string"
    },
    "setCurrent": {
      "type": "string"
    },
    "ntp": {
      "type": "string"
    },
    "serverFromDhcp": {
      "type": "string"
    },
    "server": {
      "type": "string"
    },
    "schedules": {
      "type": "string"
    },
    "noSchedules": {
      "type": "string"
    },
    "addSchedule": {
      "type": "string"
    },
    "action": {
      "type": "string"
    },
    "enableCharging": {
      "type": "string"
    },
    "chargerAvailable": {
      "type": "string"
    },
    "chargingCurrent6A": {
      "type": "string"
    },
    "chargingCurrent8A": {
      "type": "string"
    },
    "chargingCurrent10A": {
      "type": "string"
    },
    "clear": {
      "type": "string"
    },
    "remove": {
      "type": "string"
    },
    "monday": {
      "type": "string"
    },
    "tuesday": {
      "type": "string"
    },
    "wednesday": {
      "type": "string"
    },
    "thursday": {
      "type": "string"
    },
    "friday": {
      "type": "string"
    },
    "saturday": {
      "type": "string"
    },
    "sunday": {
      "type": "string"
    },
    "root": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "size": {
      "type": "string"
    },
    "download": {
      "type": "string"
    },
    "edit": {
      "type": "string"
    },
    "_delete": {
      "type": "string"
    },
    "emptyDirectory": {
      "type": "string"
    },
    "createDirectory": {
      "type": "string"
    },
    "createFile": {
      "type": "string"
    },
    "uploadFile": {
      "type": "string"
    },
    "fileName": {
      "type": "string"
    },
    "directoryName": {
      "type": "string"
    },
    "fileContent": {
      "type": "string"
    },
    "fileSaved": {
      "type": "string"
    },
    "directorySaved": {
      "type": "string"
    },
    "fileDeleted": {
      "type": "string"
    },
    "directoryDeleted": {
      "type": "string"
    },
    "fileUploaded": {
      "type": "string"
    },
    "fileTooLarge": {
      "type": "string"
    },
    "components": {
      "type": "string"
    },
    "noComponents": {
      "type": "string"
    },
    "configuration": {
      "type": "string"
    },
    "noComponentConfig": {
      "type": "string"
    },
    "autoReload": {
      "type": "string"
    },
    "output": {
      "type": "string"
    },
    "restart": {
      "type": "string"
    },
    "confirmRestart": {
      "type": "string"
    },
    "firmware": {
      "type": "string"
    },
    "channel": {
      "type": "string"
    },
    "checkForUpdate": {
      "type": "string"
    },
    "upgradeTo": {
      "type": "string"
    },
    "noUpdateAvailable": {
      "type": "string"
    },
    "uploadFirmware": {
      "type": "string"
    },
    "binariesFromReleases1": {
      "type": "string"
    },
    "binariesFromReleases2": {
      "type": "string"
    },
    "writeFirmware": {
      "type": "string"
    },
    "willBeRestart": {
      "type": "string"
    },
    "reloadInSeconds1": {
      "type": "string"
    },
    "reloadInSeconds2": {
      "type": "string"
    },
    "reloadNow": {
      "type": "string"
    },
    "successfullyUpdatedFirmware": {
      "type": "string"
    },
    "successfullyUpdated": {
      "type": "string"
    },
    "scriptReloaded": {
      "type": "string"
    },
    "networkError": {
      "type": "string"
    },
    "reloadPage": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "touch": {
      "type": "string"
    },
    "flashSize": {
      "type": "string"
    },
    "noNextionConnected": {
      "type": "string"
    },
    "uploadProgram": {
      "type": "string"
    },
    "writeProgram": {
      "type": "string"
    },
    "staticIp": {
      "type": "string"
    },
    "gateway": {
      "type": "string"
    },
    "netmask": {
      "type": "string"
    },
    "dns": {
      "type": "string"
    },
    "wifiAccessPoint": {
      "type": "string"
    },
    "wifiAccessPointAutoStop": {
      "type": "string"
    },
    "wifiStation": {
      "type": "string"
    },
    "discovery": {
      "type": "string"
    },
    "hostname": {
      "type": "string"
    },
    "instanceName": {
      "type": "string"
    },
    "rssi": {
      "type": "string"
    },
    "panicReboot": {
      "type": "string"
    },
    "acknowledge": {
      "type": "string"
    },
    "successfullyAcknowledged": {
      "type": "string"
    },
    "httpErrorValues": {
      "type": "object",
      "properties": {
        "400": {
          "type": "string"
        },
        "404": {
          "type": "string"
        },
        "413": {
          "type": "string"
        },
        "415": {
          "type": "string"
        },
        "500": {
          "type": "string"
        },
        "512": {
          "type": "string"
        },
        "513": {
          "type": "string"
        },
        "520": {
          "type": "string"
        },
        "521": {
          "type": "string"
        },
        "522": {
          "type": "string"
        },
        "523": {
          "type": "string"
        },
        "531": {
          "type": "string"
        },
        "532": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "400",
        "404",
        "413",
        "415",
        "500",
        "512",
        "513",
        "520",
        "521",
        "522",
        "523",
        "531",
        "532"
      ]
    },
    "errorValues": {
      "type": "object",
      "properties": {
        "pilot_fault": {
          "type": "string"
        },
        "diode_short": {
          "type": "string"
        },
        "lock_fault": {
          "type": "string"
        },
        "unlock_fault": {
          "type": "string"
        },
        "rcm_triggered": {
          "type": "string"
        },
        "rcm_selftest_fault": {
          "type": "string"
        },
        "temperature_high": {
          "type": "string"
        },
        "temperature_fault": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "pilot_fault",
        "diode_short",
        "lock_fault",
        "unlock_fault",
        "rcm_triggered",
        "rcm_selftest_fault",
        "temperature_high",
        "temperature_fault"
      ]
    },
    "energyMeterValues": {
      "type": "object",
      "properties": {
        "cur_vlt": {
          "type": "string"
        },
        "cur": {
          "type": "string"
        },
        "none": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "cur_vlt",
        "cur",
        "none"
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "nav",
    "pendingAuthorization",
    "chargingLimitReached",
    "evConnected",
    "charging",
    "error",
    "notAvailable",
    "evNotConnected",
    "sessionTime",
    "chargingTime",
    "power",
    "consumption",
    "totalConsumption",
    "resetTotalConsumption",
    "confirmResetTotalConsumption",
    "enabled",
    "authorize",
    "sessionLimit",
    "underPower",
    "none",
    "$none",
    "yes",
    "no",
    "submit",
    "reset",
    "reload",
    "cancel",
    "status",
    "deviceInfo",
    "uptime",
    "temperature",
    "temperatureSensorCount",
    "version",
    "dateOfBuild",
    "idfVersion",
    "ip",
    "mac",
    "chip",
    "chipCores",
    "chipRevision",
    "heap",
    "moreDetails",
    "free",
    "allocated",
    "largestFreeBlock",
    "minFree",
    "deviceName",
    "proximity",
    "socketLock",
    "rcm",
    "energyMeter",
    "energyMeterThreePhases",
    "auxInputs",
    "auxOutputs",
    "auxAnalogInputs",
    "serials",
    "maxChargingCurrent",
    "chargingCurrent",
    "consumptionLimit",
    "chargingTimeLimit",
    "underPowerLimit",
    "requireAuth",
    "socketOutlet",
    "temperatureThreshold",
    "operatingTime",
    "breakTime",
    "retryCount",
    "detection",
    "unlockedHigh",
    "lockedHigh",
    "mode",
    "dummy",
    "currentSensing",
    "currentAndVoltageSensing",
    "acVoltage",
    "threePhases",
    "ssid",
    "user",
    "password",
    "loading",
    "uploading",
    "noWifiFound",
    "systemLogs",
    "modbus",
    "nextionDisplay",
    "script",
    "atCommands",
    "baudRate",
    "dataBits",
    "stopBits",
    "parity",
    "disable",
    "even",
    "odd",
    "tcpServer",
    "unitId",
    "timezone",
    "time",
    "setCurrent",
    "ntp",
    "serverFromDhcp",
    "server",
    "schedules",
    "noSchedules",
    "addSchedule",
    "action",
    "enableCharging",
    "chargerAvailable",
    "chargingCurrent6A",
    "chargingCurrent8A",
    "chargingCurrent10A",
    "clear",
    "remove",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "root",
    "name",
    "size",
    "download",
    "edit",
    "_delete",
    "emptyDirectory",
    "createDirectory",
    "createFile",
    "uploadFile",
    "fileName",
    "directoryName",
    "fileContent",
    "fileSaved",
    "directorySaved",
    "fileDeleted",
    "directoryDeleted",
    "fileUploaded",
    "fileTooLarge",
    "components",
    "noComponents",
    "configuration",
    "noComponentConfig",
    "autoReload",
    "output",
    "restart",
    "confirmRestart",
    "firmware",
    "channel",
    "checkForUpdate",
    "upgradeTo",
    "noUpdateAvailable",
    "uploadFirmware",
    "binariesFromReleases1",
    "binariesFromReleases2",
    "writeFirmware",
    "willBeRestart",
    "reloadInSeconds1",
    "reloadInSeconds2",
    "reloadNow",
    "successfullyUpdatedFirmware",
    "successfullyUpdated",
    "scriptReloaded",
    "networkError",
    "reloadPage",
    "model",
    "touch",
    "flashSize",
    "noNextionConnected",
    "uploadProgram",
    "writeProgram",
    "staticIp",
    "gateway",
    "netmask",
    "dns",
    "wifiAccessPoint",
    "wifiAccessPointAutoStop",
    "wifiStation",
    "discovery",
    "hostname",
    "instanceName",
    "rssi",
    "panicReboot",
    "acknowledge",
    "successfullyAcknowledged",
    "httpErrorValues",
    "errorValues",
    "energyMeterValues"
  ]
}

=== dzurikmiroslav/esp32-evse-web-i18n/fr.json
{
  "nav": {
    "home": "Accueil",
    "settings": "Paramètres",
    "about": "À propos",
    "charging": "Recharge",
    "network": "Network",
    "serial": "Série",
    "modbus": "Modbus",
    "scheduler": "Planificateur",
    "files": "Fichiers",
    "script": "Script",
    "management": "Gestion",
    "system": "Système",
    "nextion": "Nextion",
    "selectLanguage": "Choisir la langue",
    "toggleTheme": "Changer de thème"
  },
  "pendingAuthorization": "Autorisation en attente",
  "chargingLimitReached": "Limite de recharge atteinte",
  "evConnected": "Véhicule connecté",
  "charging": "Recharge en cours",
  "error": "Erreur",
  "notAvailable": "Non disponible",
  "evNotConnected": "Véhicule non connecté",
  "sessionTime": "Durée de la session",
  "chargingTime": "Temps de recharge",
  "power": "Puissance",
  "consumption": "Consommation",
  "totalConsumption": "Consommation totale",
  "resetTotalConsumption": "Réinitialiser consommation totale",
  "confirmResetTotalConsumption": "Réinitialiser consommation totale ?",
  "enabled": "Activé",
  "authorize": "Autoriser",
  "sessionLimit": "Limite de session",
  "underPower": "Sous-alimentation",
  "none": "Aucun",
  "$none": "aucun",
  "yes": "Oui",
  "no": "Non",
  "submit": "Valider",
  "reset": "Réinitialiser",
  "reload": "Recharger",
  "cancel": "Annuler",
  "status": "Statut",
  "deviceInfo": "Informations sur l'appareil",
  "uptime": "Temps de fonctionnement",
  "temperature": "Température",
  "temperatureSensorCount": "Nombre de capteurs de température",
  "version": "Version",
  "dateOfBuild": "Date de compilation",
  "idfVersion": "Version IDF",
  "ip": "IP",
  "mac": "Adresse MAC",
  "chip": "Puce",
  "chipCores": "Noyaux de la puce",
  "chipRevision": "Révision de la puce",
  "heap": "Mémoire disponible",
  "moreDetails": "Plus de détails",
  "free": "Libre",
  "allocated": "Alloué",
  "largestFreeBlock": "Plus grand bloc libre",
  "minFree": "Minimum libre",
  "deviceName": "Nom de l'appareil",
  "proximity": "Pilote de proximité",
  "socketLock": "Verrouillage de la prise",
  "rcm": "Contrôleur de courant résiduel",
  "energyMeter": "Compteur d'énergie",
  "energyMeterThreePhases": "Compteur d'énergie triphasé",
  "auxInputs": "Entrée AUX",
  "auxOutputs": "Sortie AUX",
  "auxAnalogInputs": "Entrée analogique AUX",
  "serials": "Série",
  "maxChargingCurrent": "Courant de recharge max",
  "chargingCurrent": "Courant de recharge",
  "consumptionLimit": "Limite de consommation",
  "chargingTimeLimit": "Limite de temps de recharge",
  "underPowerLimit": "Limite de sous-alimentation",
  "requireAuth": "Nécessite une autorisation",
  "socketOutlet": "Prise de courant",
  "temperatureThreshold": "Seuil de température",
  "operatingTime": "Temps de fonctionnement",
  "breakTime": "Temps de pause",
  "retryCount": "Nombre de tentatives",
  "detection": "Détection",
  "unlockedHigh": "Déverrouillé haut",
  "lockedHigh": "Verrouillé haut",
  "mode": "Mode",
  "dummy": "Factice",
  "currentSensing": "Détection de courant",
  "currentAndVoltageSensing": "Détection de courant et tension",
  "acVoltage": "Tension AC",
  "threePhases": "Triphasé",
  "ssid": "SSID",
  "user": "Utilisateur",
  "password": "Mot de passe",
  "loading": "Chargement...",
  "uploading": "Teléversement...",
  "noWifiFound": "Aucun Wi-Fi trouvé",
  "systemLogs": "Journaux système",
  "modbus": "Modbus",
  "nextionDisplay": "Affichage Nextion",
  "script": "Script",
  "atCommands":"Commandes AT",
  "baudRate": "Débit en bauds",
  "dataBits": "Bits de données",
  "stopBits": "Bits d'arrêt",
  "parity": "Parité",
  "disable": "Désactiver",
  "even": "Paire",
  "odd": "Impaire",
  "tcpServer": "Serveur TCP",
  "unitId": "ID unité",
  "timezone": "Fuseau horaire",
  "time": "Heure",
  "setCurrent": "Définir le courant",
  "ntp": "NTP",
  "serverFromDhcp": "Serveur depuis DHCP",
  "server": "Serveur",
  "schedules": "Plannings",
  "noSchedules": "Aucun planning",
  "addSchedule": "Ajouter un horaire",
  "action": "Action",
  "enableCharging": "Activer la recharge",
  "chargerAvailable": "Chargeur disponible",
  "chargingCurrent6A": "Courant de recharge 6A",
  "chargingCurrent8A": "Courant de recharge 8A",
  "chargingCurrent10A": "Courant de recharge 10A",
  "clear": "Effacer",
  "remove": "Supprimer",
  "monday": "Lun",
  "tuesday": "Mar",
  "wednesday": "Mer",
  "thursday": "Jeu",
  "friday": "Ven",
  "saturday": "Sam",
  "sunday": "Dim",
  "root": "Racine",
  "name": "Nom",
  "size": "Taille",
  "download": "Télécharger",
  "edit": "Modifier",
  "_delete": "Supprimer",
  "emptyDirectory": "Le dossier est vide",
  "createDirectory": "Créer un répertoire",
  "createFile": "Créer un fichier",
  "uploadFile": "Envoyer un fichier",
  "fileName": "Nom du fichier",
  "directoryName": "Nom du répertoire",
  "fileContent": "Contenu du fichier",
  "fileSaved": "Fichier enregistré",
  "directorySaved": "Fichier enregistré",
  "fileDeleted": "Fichier supprimé",
  "directoryDeleted": "Répertoire supprimé",
  "fileUploaded": "Fichier envoyé avec succès",
  "fileTooLarge": "Le fichier sélectionné est trop volumineux",
  "components": "Composants",
  "noComponents": "Pas de composants",
  "configuration": "Configuration",
  "noComponentConfig": "Le composant n'a pas de configuration",
  "autoReload": "redémarrage automatique",
  "output": "Sortie",
  "restart": "Redémarrer",
  "confirmRestart": "Confimer le redémarrage?",
  "firmware": "Micrologiciel",
  "channel": "Canal",
  "checkForUpdate": "Vérifier les mises à jour",
  "upgradeTo": "Mettre à jour vers",
  "noUpdateAvailable": "Aucune mise à jour disponible",
  "uploadFirmware": "Envoyer le micrologiciel",
  "binariesFromReleases1": "utiliser les binaires depuis",
  "binariesFromReleases2": "versions",
  "writeFirmware": "Écrire le micrologiciel",
  "willBeRestart": "L'appareil va redémarrer",
  "reloadInSeconds1": "Rechargement dans",
  "reloadInSeconds2": "secondes",
  "reloadNow": "Recharger maintenant",
  "successfullyUpdatedFirmware": "Micrologiciel mis à jour avec succès",
  "successfullyUpdated": "Mis à jour avec succès",
  "scriptReloaded": "Script rechargé",
  "networkError": "Erreur réseau",
  "reloadPage": "Recharger la page",
  "model": "Modèle",
  "touch": "Tactile",
  "flashSize": "Taille mémoire flash",
  "noNextionConnected": "Aucun affichage Nextion connecté",
  "uploadProgram": "Téléverser le programme",
  "writeProgram": "Ecrire le programme",
  "staticIp": "Adresse IP statique",
  "gateway": "Passerelle",
  "netmask": "Masque de sous-réseau",
  "dns": "Serveur DNS",
  "wifiAccessPoint": "Point d'accès WiFi",
  "wifiAccessPointAutoStop": "Le point d'accès s'éteindra automatiquement si personne ne s'y connecte dans la minute.",
  "wifiStation": "Station WiFi",
  "discovery": "Découverte",
  "hostname": "Nom d'hôte",
  "instanceName": "Nom de l'instance",
  "rssi": "RSSI",
  "panicReboot": "Redémarrage panique",
  "acknowledge": "Acquitter",
  "successfullyAcknowledged": "Acquitté avec succès",
  "httpErrorValues": {
    "400": "Requête incorrecte",
    "404": "Non trouvé",
    "413": "Contenu trop volumineux",
    "415": "Type de média non supporté",
    "500": "Erreur interne du serveur",
    "512": "Échec d'allocation mémoire",
    "513": "Échec de réception de la requête",
    "520": "Impossible de récupérer les informations de la dernière version",
    "521": "Échec de la mise à jour du micrologiciel",
    "522": "Échec de réception du micrologiciel",
    "523": "Fichier de micrologiciel invalide",
    "531": "Échec de réception du fichier",
    "532": "Échec d'écriture du fichier"
  },
  "errorValues": {
    "pilot_fault": "Défaillance du pilote",
    "diode_short": "Court-circuit de la diode",
    "lock_fault": "Défaillance du verrouillage",
    "unlock_fault": "Défaillance du déverrouillage",
    "rcm_triggered": "RCM déclenché",
    "rcm_selftest_fault": "Défaillance de l'autotest du RCM",
    "temperature_high": "Température élevée",
    "temperature_fault": "Défaillance du capteur de température"
  },
  "energyMeterValues": {
    "cur_vlt": "Courant et tension",
    "cur": "Courant",
    "none": "Aucun"
  }
}
